default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: db
  username: postgres

development:
  <<: *local
  database: nyaku_development

test:
  <<: *local
  database: nyaku_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
